config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:password, :registrations, :sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root 'home#index'

  resources :galeries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/galery.rb
class Galery < ApplicationRecord
  mount_uploader :file, FileUploader

  before_create :set_metadata

  private

    def set_metadata
      uploaded_file = self.file
      if uploaded_file.content_type == 'image/jpeg'
        creation_date = EXIFR::JPEG.new(uploaded_file.file.file).date_time

        unless creation_date.nil?
          self.created_at = creation_date.strftime("%Y.%m.%d %I:%M%P")
        end
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :fname, presence: true, length: { minimum: 2, maximum: 50 }
  validates :lname, presence: true, length: { minimum: 2, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/galeries_controller.rb
class GaleriesController < ApplicationController
  def index
    @galery = Galery.new
    @galery_files = Galery.all.order(created_at: :desc)
  end

  def show

  end

  def new

  end

  def create
    @galery = Galery.create!(galery_params)
    redirect_to galeries_path
  end

  def update

  end

  def destroy

  end

  private

    def galery_params
      params.require(:galery).permit(:file)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galery_helper.rb
module GaleryHelper\
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galeries/_galery.html.erb
<div id="<%= dom_id(galery) %>" class="col p-2 fake">
  <%= link_to galery_path(galery) do %>
    <% if ['jpg', 'png', 'gif' 'jpeg'].include?(galery.file.file.extension) %>
      <%= image_tag galery.file.url, class: 'picture-preview',
                                                                width: '100%' %>
    <% elsif ['wmv', 'mp4'].include?(galery.file.file.extension) %>
      <%= video_tag galery.file.url, class: 'picture-preview', width: '100%' %>
    <% end %>
  <% end %>
</div>

app/views/galeries/_galery_modal.html.erb
<div class="galery-modal">

</div>

app/views/galeries/index.html.erb
<div class="row mx-2 mx-lg-5 d-flex flex-wrap">
  <h1 class="text-center p-3 color-white">Hello, here is your media files!</h1>
  <%= form_for @galery do |f| %>
    <%= f.label 'Upload file', for: 'galery_file', class: 'm-2 position-fixed fixed-button' %>
    <%= f.file_field :file, hidden: '', onchange: 'form.submit()' %>
  <% end %>
  <%= render @galery_files %>
</div>

app/views/galeries/show.turbo_stream.erb
<%= turbo_stream.replace(
  'galery-modal',
  partial: 'galeries/'
) %>

app/views/home/index.html.erb
<h1>Hello buddy 😜</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HuntiCloud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="bg">
        <div class="container-fluid h-100">
          <div class="row h-100">
            <%= render 'shared/navbar' %>
            <main class="col bg-content">
              <%= yield %>
            </main>
          </div>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<aside class="col-12 col-xl-2 bg-navbar p-0">
  <nav class="navbar navbar-expand-xl navbar-dark flex-xl-column flex-row
                                                  align-items-start p-2 p-xl-4">
    <div class="container-fluid">
      <div class="d-flex flex-wrap w-100">
        <div class="flex-nowrap row w-100">
          <a class="navbar-brand col-10 col-lg-11" href="#">HuntiCloud</a>
          <button class="navbar-toggler col-2 col-lg-1 p-1" type="button"
                                               data-bs-toggle="collapse"
                                               data-bs-target="#navbarNavAltMarkup"
                                               aria-controls="navbarNavAltMarkup"
                                               aria-expanded="false"
                                               aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="flex-xl-column flex-row navbar-nav row px-4">
            <%= link_to 'Home',root_path,
                        class: "nav-link #{ params[:controller] == 'home' &&
                                params[:action] == 'index' ? 'active' : '' }" %>
            <%= link_to 'Galery', galeries_path,
                        class: "nav-link #{ params[:controller] == 'galeries' &&
                                params[:action] == 'index' ? 'active' : '' }" %>
            <%= link_to_if( params[:controller] == 'galeries' &&
                           params[:action] == 'index', 'Partners', '#',
                                         class: 'nav-link disabled ms-2 pt-0 fs-6 lh-1',
                                         aria: { disabled: true } ) {} %>
            <%= link_to 'Tools', '#',
                        class: 'nav-link disabled', aria: { disabled: true } %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</aside>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>